# Generated by Django 3.1.7 on 2021-03-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='media')),
                ('data_criacao', models.DateField(auto_now=True)),
            ],
        ),
    ]
