# Generated by Django 3.1.7 on 2021-03-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='item',
        ),
    ]
